### ISSUE TITLE
Disk upload failing due to bogus unclean shutdown in current master

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#781] opened 2016-07-09 00:57 UTC
I've updated our staging openQA to the current git master for both openqa and os-autoinst: 7a1901d0c122345d80a68a0f1ffbe5ac5e6e6ddd for os-autoinst and 84c94613212c33aeca1c663a2f6c828bc3c17161 for openQA. Something - I think @coolo 's shutdown rework - appears to have broken disk upload. Check out [this test](https://openqa.stg.fedoraproject.org/tests/27871) - it passes perfectly, including an `assert_shutdown()`, yet disk upload fails:

    22:15:01.4772 21795 sysread failed: 
    22:15:01.4783 21795 THERE IS NOTHING TO READ 12 12 11
    22:15:01.4787 21795 awaiting death of testpid 21800
    22:15:01.4797 21795 21795: got sigchld
    22:15:01.4798 21795 isotovideo done
    waitpid for 21837 returned 0
    sending TERM to qemu pid: 21837
    waitpid for 21837 returned 21837
    22:15:02.6196 21821 QEMU: qemu-system-x86_64: terminating on signal 15 from pid 21821
    sending magic and exit
    received magic close
    22:15:02.6416 21795 21795: got sigchld
    22:15:02.6418 21795 killing commands process
    22:15:02.6454 21795 21795: got sigchld
    22:15:02.6455 21795 done joining commands process
    22:15:02.6455 21795 ERROR: Machine not shut down when uploading disks!

The production deployment, where this is not happening, is running git c34c90b . Comparing logs with a similar test from production - https://openqa.fedoraproject.org/tests/25021 - we can see that those 'sysread failed' messages are not present there.

**Comment by coolo** [comment] 2016-07-09 05:25
it means the tests are done - but the VM is not stopped correctly before the kills.

**Comment by AdamWill** [comment] 2016-07-09 05:46
But we're using the same test in prod and stg, and the test has an `assert_shutdown()`, which passes:

    22:14:57.4074 21800 <<< testapi::assert_shutdown(timeout=60)
    22:14:57.4080 21821 EVENT {"timestamp":{"microseconds":94662,"seconds":1468015568},"data":{"path":"/machine/peripheral-anon/device[0]/virtio-backend"},"event":"NIC_RX_FILTER_CHANGED"}
    22:14:57.4081 21821 EVENT {"timestamp":{"microseconds":330144,"seconds":1468015998},"event":"RESET"}
    22:14:57.4082 21821 EVENT {"timestamp":{"microseconds":345272,"seconds":1468015998},"event":"RESET"}
    22:14:57.4083 21821 EVENT {"timestamp":{"seconds":1468016072,"microseconds":442594},"event":"STOP"}
    22:14:57.4083 21821 EVENT {"timestamp":{"microseconds":760552,"seconds":1468016080},"event":"RESUME"}
    22:15:01.4147 21821 EVENT {"timestamp":{"seconds":1468016100,"microseconds":433287},"event":"SHUTDOWN"}
    22:15:01.4149 21821 EVENT {"event":"STOP","timestamp":{"seconds":1468016100,"microseconds":434283}}
    22:15:01.4767 21800 ||| finished _console_shutdown tests at 2016-07-08 22:15:01 (21 s)

**Comment by coolo** [comment] 2016-07-09 06:50
but as you can see in your log above, qemu was still killed hard. I.e. the SUT was down, but qemu was not ready yet

**Comment by coolo** [comment] 2016-07-09 10:43
But at least it seems 100% reproducible on my staging

**Comment by coolo** [comment] 2016-07-09 19:09
ok, the problem is actually much simpler. but I found tons of problems on the way of finding it :)

**Comment by AdamWill** [comment] 2016-07-09 19:31
congratulations on breaking all the things! ;)

**Comment by coolo** [comment] 2016-07-09 20:00
Give https://github.com/os-autoinst/os-autoinst/pull/534 a try - it still fails here, but possibly you can find out more

**Comment by AdamWill** [comment] 2016-07-09 20:25
ok, I'll throw it on our staging instance later today. you go do some weekend stuff! get outta here

**Comment by coolo** [comment] 2016-07-10 12:33
fixed in os-autoinst/os-autoinst#534 in my tests

**Closed by coolo** 2016-07-10 12:33 UTC

**Comment by AdamWill** [comment] 2016-07-10 14:42
Initial testing looks good here too, we'll see how it goes over a few days.
