### ISSUE TITLE
Live view gets stuck when nothing happens for a while

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#768] opened 2016-07-05 01:54 UTC
I've noticed that quite often if I'm watching the live view of a test but nothing happens for a while - that is, the screen does not change - the live view will stick and stop refreshing. I have to force a refresh with shift-ctrl-r to get it going again.

**Comment by coolo** [comment] 2016-07-05 05:15
I think that's because the logo is still not proper SVG.

**Comment by okurz** [comment] 2016-07-05 05:30
On Monday 04 July 2016 22:15:16 Stephan Kulow wrote:
> I think that's because the logo is still not proper SVG.

I just crosschecked: Replacing the logo by the openSUSE one did not just fix 
this problem but many more … just kidding ;-)

**Comment by AdamWill** [comment] 2016-07-05 05:47
sounds plausible ;)

sorry guys, I'll poke mizmo tomorrow, promise...

**Comment by coolo** [comment] 2016-12-22 07:22
I assume your browser is just protecting you from OOM. And I have very little motivation to keep live views running for hours to even reproduce it. So I'm closing

**Closed by coolo** 2016-12-22 07:22 UTC

**Comment by AdamWill** [comment] 2016-12-22 07:32
it was nothing like hours, just if the job stays on the same screen for say 10-15 seconds. but if it bugs me again, I guess I'll try and figure it out.
