### ISSUE TITLE
[Script: dump_templates], Failed to load template file with json format , cause "Error in data file: syntax error at /tmp/dump.ts line 2,"

### ISSUE THREAD

**Issue by XGWang0** [os-autoinst/openQA#699] opened 2016-05-31 09:33 UTC
Hi:
The script ./dump_templates can not load json template file.
Reproduce step:
1. Dump a existing test suite as a template file  with json formate.
./dump_templates --test qemu_create_hdd --json  > /tmp/dump.ts
2. Load template.
./load_templates /tmp/dump.ts

Issue happens and input "Error in data file: syntax error at /tmp/dump.ts line 2"

**Comment by aaannz** [comment] 2016-05-31 11:19
If you want to use json file use `.json` extension. That's how load_templates determines it is the json content.

**Comment by XGWang0** [comment] 2016-06-01 06:41
Got it , thanks  Ondřej Holeček
 
>>> Ondřej Holeček <notifications@github.com> 5/31/2016 07:19 PM >>> 
If you want to use json file use `.json` extension. That's how load_templates determines it is the json content.

---

**Comment by okurz** [comment] 2016-06-08 18:32
please close if the issue is solved for you

**Comment by aaannz** [comment] 2016-06-09 09:23
Lets close this and @XGWang0 can reopen in case of issues.

**Closed by aaannz** 2016-06-09 09:23 UTC
